version: "2"
services:
  web:
    hostname: blog.camicado.dev
    build: ./
    ports:
      - "80:80"
    volumes:
      - ../:/app
      - ../gerador:/var/www/html/gerador
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: gerador_camica
      MYSQL_USER: gerador_camica
      MYSQL_PASSWORD: oE!7KK@ZMPpt
      MYSQL_ROOT_PASSWORD: oE!7KK@ZMPpt
    ports:
      - "3306:3306"
